feat : Simulation parts
steamicc/makecode-steami pull request #1
Opened 2024-10-07 09:58 UTC by Charly-sketch

2024-10-08 08:09 UTC, nedseb commented
@Charly-sketch 
Je vais réécrire l'historique git de ta PR pour le rendre plus explicite. Pense à récupérer la dernière version avant de faire les modifications que je te proposerai dans la phase de review.

2024-10-08 08:13 UTC, Charly-sketch commented
Ok pas de soucis

Le mar. 8 oct. 2024, 10:09, Sébastien NEDJAR ***@***.***> a
écrit :

> Assigned #1 <https://github.com/steamicc/makecode-steami/pull/1> to
> @Charly-sketch <https://github.com/Charly-sketch>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/steamicc/makecode-steami/pull/1#event-14552183882>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCU5K7YQKWZTVX3RGMFQVN3Z2OHNDAVCNFSM6AAAAABPPRH37GVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGU2TEMJYGM4DQMQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-10-08 08:25 UTC, nedseb commented on pxt-steami/pxtarget.json
> -        "onStartNamespace": "basic",
Pourquoi n'as-tu pas précisé l'espace de nom qui doit être ouvert quand tu ouvres ton éditeur ?

2024-10-08 08:29 UTC, nedseb commented on pxt-steami/pxtarget.json
> +                "P20": "P20"
Il faudra rajouter une issue pour les pins manquants

2024-10-08 08:30 UTC, nedseb commented on pxt-steami/pxtarget.json
> +                "microphone"
Tu as déjà tous ces éléments dans ta simulation ? Peut-être qu'il vaudrait mieux les ajouter un à un. Pour ne pas oublier, tu peux créer une issue pour chacun

2024-10-08 08:32 UTC, nedseb commented on pxt-steami/pxtarget.json
> +            }
J'ai pas les mêmes valeurs de vid et pid pour la STeaMi(0d28:0204). Tu sais à quoi ça sert de mettre ces valeurs ?

2024-10-08 08:34 UTC, nedseb commented on pxt-steami/sim/dalboard.ts
> +        export let RX = -1;
C'est pas génant que les pins dans la simulation ne s'appellent pas comme ceux de la definition de la board dans le fichier `pxtarget.json` ?

2024-10-08 08:35 UTC, nedseb commented on pxt-steami/sim/dalboard.ts
> +            // TODO
Penses à être précis sur tes TODO. Là si je viens après toi, je ne peux pas savoir ce qu'il manque

2024-10-08 08:40 UTC, nedseb commented on pxt-steami/sim/public/workerCongig.js
> +})
Je pense qu'il y a un problème sur le nom de fichier....

2024-10-08 08:42 UTC, nedseb commented on pxt-steami/sim/visuals/board.ts
> +    const MB_STYLE = `
Peut-être que `STEAMI_STYLE` pourrait être plus raccord ^^

2024-10-08 08:44 UTC, nedseb commented on pxt-steami/sim/visuals/board.ts
> +    ];
Les `name` ne pourraient-ils pas être plus explicites ?

2024-10-08 08:45 UTC, nedseb commented on pxt-steami/sim/visuals/board.ts
> +    const MB_HEIGHT = 316.30045;
MB_->STEAMI_

2024-10-08 08:49 UTC, nedseb requested changes
Je viens de faire une première passe de relecture. Je t'ai déjà mis pas mal de questions, je te laisse y répondre et/ou faire les modifications nécéssaire. 

Comme remarque globale, j'ai l'impression que tu inclues trop de fonctionnalités dans ton board.ts pour une première PR.

2024-10-08 09:34 UTC, Charly-sketch commented on pxt-steami/pxtarget.json
> +            }
C'est valeur sont un oublie venant du boardDefinition d'adaxfruit. Elle sert à spécifier des informations liées au changement de vitesse de transmission (baudrate) lors de la communication avec le bootloader, peut aider à résoudre des problèmes de flash sur certaine carte.

2024-10-08 12:52 UTC, Charly-sketch commented on pxt-steami/sim/dalboard.ts
> +        export let RX = -1;
Pas forcément, elles devront l'être pour plus de lisibilité mais c'est pins sont définis dans le namespace config.

2024-10-08 13:21 UTC, Charly-sketch commented on pxt-steami/sim/public/workerCongig.js
> +})
Sur let's Steam et adaxfruit le fichier est définis comme ça mais sur Micro-bit il n'est juste pas définis. J'ai essayé de le supprimer tout semble fonctionner comme avant.

2024-10-08 13:45 UTC, Charly-sketch commented on pxt-steami/sim/visuals/board.ts
> +    const MB_STYLE = `
[79c3a1f](https://github.com/steamicc/makecode-steami/pull/1/commits/79c3a1f76cc2d5b36c4625e4b75ecc85cdd91006)

2024-10-08 13:45 UTC, Charly-sketch commented on pxt-steami/sim/visuals/board.ts
> +    const MB_HEIGHT = 316.30045;
[4fa54ec](https://github.com/steamicc/makecode-steami/pull/1/commits/4fa54ec5bab997eddbe3755169032c4af6ae62d2)

2024-10-08 13:47 UTC, Charly-sketch commented on pxt-steami/sim/dalboard.ts
> +            // TODO
[d9c1c8c](https://github.com/steamicc/makecode-steami/pull/1/commits/d9c1c8c6e167e2f1fa29f23c52048cf8cfa6be1a)
[dd56e13](https://github.com/steamicc/makecode-steami/pull/1/commits/dd56e13c7cded85f8d65437c5f006df8724ce9a6)

2024-10-08 13:48 UTC, Charly-sketch commented on pxt-steami/pxtarget.json
> +            }
[0cb3eb5](https://github.com/steamicc/makecode-steami/pull/1/commits/0cb3eb50920eb342f8af5845f6170da627e8a0fb)

2024-10-08 13:48 UTC, Charly-sketch commented on pxt-steami/pxtarget.json
> -        "onStartNamespace": "basic",
[9be59fb](https://github.com/steamicc/makecode-steami/pull/1/commits/9be59fb394855c84f2b23e6722cd4d3641882689)

2024-10-09 13:33 UTC, nedseb approved these changes

2024-10-09 14:36 UTC, merged