Charly led rgb
steamicc/makecode-steami pull request #3
Opened 2024-10-07 10:00 UTC by Charly-sketch

2024-10-10 08:53 UTC, nedseb commented on pxt-steami/libs/core/enums.d.ts
> +    LED_ble = 3,
pourquoi ble en minuscule ?

2024-10-10 08:54 UTC, nedseb commented on pxt-steami/libs/core/leds.cpp
> +    LED_ble = 3,
Pourquoi ble en minuscule ?

2024-10-10 08:57 UTC, nedseb requested changes
mis à part une correction mineure, ça devrait être bon

2024-10-10 08:57 UTC, nedseb commented on pxt-steami/libs/core/leds.cpp
> +    LED_DAPLINK = 5,
Pourquoi tu as mis les LED qui ne sont pas programmables ?

2024-10-10 09:14 UTC, Charly-sketch commented on pxt-steami/libs/core/enums.d.ts
> +    LED_ble = 3,
Ça vient d'un ancien conflit avec un enum leds qui déclarait déjà cette led. Mais vu qu'il n'y a que cette led de programmable, je n'aurais plus besoins de cet enum.

2024-10-10 09:19 UTC, Charly-sketch commented on pxt-steami/libs/core/enums.d.ts
> +    LED_ble = 3,
[0eafa02](https://github.com/steamicc/makecode-steami/pull/3/commits/0eafa028014c614e757cce6ac9dd9d6c89132440)

2024-10-10 09:19 UTC, Charly-sketch commented on pxt-steami/libs/core/leds.cpp
> +    LED_ble = 3,
[0eafa02](https://github.com/steamicc/makecode-steami/pull/3/commits/0eafa028014c614e757cce6ac9dd9d6c89132440)

2024-10-25 10:51 UTC, nedseb approved these changes

2024-10-25 10:51 UTC, merged